### ISSUE TITLE
Menú Usuario

### ISSUE THREAD

**Issue by UO247134** [UO247134/GameGallery#4]
Se necesita crear una pantalla para mostrar información del usuario y un botón desde donde acceder a esta.
Información a mostrar:
1) Nickname
2) Correo
3) Avatar
4) Lista de Plataformas de interés que ha escogido

**Comment by oscar134** [comment]
Al iniciar sesión deben ponerse las preferencias del usuario en la clase Info.

**Comment by oscar134** [comment]
La sesión puede ya iniciarse, pero el Navigation Drawer Header no se actualiza. Todavía falta registrarse y manejar las preferencias de usuario, así como poder modificar sus datos en Settings

**Comment by oscar134** [comment]
Funciona todo excepto el avatar, ya que la base de datos no guarda imagenes
