### ISSUE TITLE
Mejorar base de datos

### ISSUE THREAD

**Issue by oscar134** [UO247134/GameGallery#6]
La base de datos debe contener más información para cada juego. 
Se deberá:
1) Convertir la plataforma en un Array con varias opciones
2) Añadir un Array de Género

**Comment by UO247134** [comment]
Posible solución, 2 nuevas tablas (Género y Plataforma) con una relación uno a muchos con Juego.
El objeto juego si contendrá los array respectivos

**Comment by oscar134** [comment]
Cada plataforma ya es un array, pero no consigo enviarla a través del Parcelable a la SecondActivity
